# Generated by Django 5.1.2 on 2025-09-15 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('passed_year', models.IntegerField()),
                ('job_role', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('connections', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid mobile number')])),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('working_company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('GENERAL', 'General Feedback'), ('WEBSITE', 'Website Improvement'), ('EVENT', 'Event Suggestions'), ('ISSUE', 'Any Issues'), ('OTHER', 'Other')])),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='alumni.alumni')),
            ],
        ),
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('job_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('app_url', models.URLField()),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
                ('skills_required', models.ManyToManyField(related_name='JobBoard', to='alumni.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.jobboard')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('mentees', models.IntegerField()),
                ('skills', models.ManyToManyField(related_name='mentors', to='alumni.skill')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='skills',
            field=models.ManyToManyField(related_name='alumni', to='alumni.skill'),
        ),
    ]
