# Generated by Django 5.1.2 on 2025-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='branch',
            field=models.CharField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
