# Generated by Django 5.1.2 on 2025-09-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_remove_alumni_password_alumni_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='l_name',
        ),
    ]
