# Generated by Django 5.1.2 on 2025-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_rename_f_name_alumni_name_remove_alumni_l_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='gender',
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
