# Generated by Django 5.1.2 on 2025-09-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_remove_alumni_gender_alumni_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='email',
        ),
    ]
